### ISSUE TITLE
java.lang.NoSuchMethodError: No static method glide

### ISSUE THREAD

**Issue by 1-riverfish** [daimajia/AnimationEasingFunctions#23]
java.lang.NoSuchMethodError: No static method glide(Lcom/daimajia/easing/Skill;FLcom/nineoldandroids/animation/ValueAnimator;)Lcom/nineoldandroids/animation/ValueAnimator; in class Lcom/daimajia/easing/Glider; or its super classes (declaration of 'com.daimajia.easing.Glider' appears in /data/app/com.seuchild.smallseedling-EKGm8F1g0YQlzLb--O6EZw==/split_lib_dependencies_apk.apk)
                      at com.github.omadahealth.circularbarpager.library.CircularBar.animateProgress(CircularBar.java:606)
                      at com.seuchild.smallseedling.health.HealthActivity.onResume(HealthActivity.java:59)
                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1457)
                      at android.app.Activity.performResume(Activity.java:7149)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3700)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3766)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2995)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6753)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I have add 
-keep class com.daimajia.easing.** { *; }
-keep interface com.daimajia.easing.** { *; }
-keepclassmembers public class * extends com.daimajia.easing.BaseEasingMethod {
    public <init>(...);
}
to proguard-project.txt file.

**Comment by housseynCheriet** [comment]
Best explanation of easing function
https://www.selectionjs.com/animation
